use_frameworks!
platform :ios, '11.0'

target 'TextBundleExample' do
  pod 'textbundle-swift', :path => '../', :testspecs => ['Tests']

  target 'TextBundleExampleTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';
  end
end
